In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('heart_2020_cleaned_copy.csv')

In [4]:
df.head()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,-1,16.60,1,-1,-1,3.0,30.0,-1,2,8,1,1,1,2,5.0,1,-1,1
1,-1,20.34,-1,-1,1,0.0,0.0,-1,2,13,1,-1,1,2,7.0,-1,-1,-1
2,-1,26.58,1,-1,-1,20.0,30.0,-1,1,10,1,1,1,4,8.0,1,-1,-1
3,-1,24.21,-1,-1,-1,0.0,0.0,-1,2,12,1,-1,-1,3,6.0,-1,-1,1
4,-1,23.71,-1,-1,-1,28.0,0.0,1,2,5,1,-1,1,2,8.0,-1,-1,-1

In [5]:
df = df.drop(['Race','DiffWalking', 'GenHealth'], axis=1)

In [6]:
df.head()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,Sex,AgeCategory,Diabetic,PhysicalActivity,SleepTime,Asthma,KidneyDisease,SkinCancer
0,-1,16.60,1,-1,-1,3.0,30.0,2,8,1,1,5.0,1,-1,1
1,-1,20.34,-1,-1,1,0.0,0.0,2,13,-1,1,7.0,-1,-1,-1
2,-1,26.58,1,-1,-1,20.0,30.0,1,10,1,1,8.0,1,-1,-1
3,-1,24.21,-1,-1,-1,0.0,0.0,2,12,-1,-1,6.0,-1,-1,1
4,-1,23.71,-1,-1,-1,28.0,0.0,2,5,-1,1,8.0,-1,-1,-1

In [9]:
linha_especifica = df.iloc[263380]

In [10]:
linha_especifica

HeartDisease        -1.00
BMI                 25.61
Smoking             -1.00
AlcoholDrinking     -1.00
Stroke              -1.00
PhysicalHealth       4.00
MentalHealth        15.00
Sex                  2.00
AgeCategory          1.00
Diabetic            -1.00
PhysicalActivity     1.00
SleepTime            8.00
Asthma               1.00
KidneyDisease       -1.00
SkinCancer          -1.00
Name: 263380, dtype: float64